### ISSUE TITLE
TEST FOR TWITTER INTERFACE

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#12]
fastest way i could test if it tweets is making an issue that will get picked up by the script. 

https://twitter.com/0x4007

**Comment by 0x4007** [comment]
```
Trace: {
  tweetText: 'undefined for undefined\n' +
    '\n' +
    'https://github.com/ubiquity/devpool-directory/issues/1024'
}
    at main (/Users/nv/repos/ubiquity/devpool-directory/index.ts:145:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Users/nv/repos/ubiquity/devpool-directory/index.ts:168:5)
Error posting tweet [
  {
    message: 'You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product',
    code: 453
  }
]
```
